/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.verrel.pertemuan1;
import java.beans.PropertyVetoException;
import id.verrel.pertemuan2.FormKaryawan;
import id.verrel.pertemuan2.FormLihatKaryawan;
import id.verrel.pertemuan3.FormPekerjaan;
import id.verrel.pertemuan3.FormLihatPekerjaan;
import id.verrel.pertemuan4.FormGaji;
import id.verrel.pertemuan6.FormLogin;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Verrel
 */
public class FormUtama extends javax.swing.JFrame {
    public static FormKaryawan formKaryawan;
    public static FormPekerjaan formPekerjaan;
    public static FormGaji formGaji;
    public static FormLaporanGaji formLaporanGaji;
    public final FormDeskripsi formDeskripsi = new FormDeskripsi(this, true);
    public final FormLogin formLogin = new FormLogin(this,true);
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormUtama.class.getName());

    /**
     * Creates new form FormUtama
     */
    public FormUtama() {
        initComponents();
        setUkuranLokasiFrame(0.8, true);
        mdiDesktopPane = new javax.swing.JDesktopPane();
        setContentPane(mdiDesktopPane);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mdiDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        aplikasiMenu = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        deskripsiMenuItem = new javax.swing.JMenuItem();
        aksesMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        keluarMenuItem = new javax.swing.JMenuItem();
        masterDataMenu = new javax.swing.JMenu();
        karyawanMenuItem = new javax.swing.JMenuItem();
        pekerjaanMenuItem = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        gajiMenuItem = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        gajiLaporanMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        karyawanLaporanMenuItem = new javax.swing.JMenuItem();
        pekerjaanLaporanMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout mdiDesktopPaneLayout = new javax.swing.GroupLayout(mdiDesktopPane);
        mdiDesktopPane.setLayout(mdiDesktopPaneLayout);
        mdiDesktopPaneLayout.setHorizontalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1119, Short.MAX_VALUE)
        );
        mdiDesktopPaneLayout.setVerticalGroup(
            mdiDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );

        aplikasiMenu.setText("Aplikasi");
        aplikasiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplikasiMenuActionPerformed(evt);
            }
        });
        aplikasiMenu.add(jSeparator1);

        deskripsiMenuItem.setText("Deskripsi");
        deskripsiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deskripsiMenuItemActionPerformed(evt);
            }
        });
        aplikasiMenu.add(deskripsiMenuItem);

        aksesMenuItem.setText("Login");
        aksesMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aksesMenuItemActionPerformed(evt);
            }
        });
        aplikasiMenu.add(aksesMenuItem);
        aplikasiMenu.add(jSeparator2);

        keluarMenuItem.setText("Keluar");
        keluarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarMenuItemActionPerformed(evt);
            }
        });
        aplikasiMenu.add(keluarMenuItem);

        jMenuBar1.add(aplikasiMenu);

        masterDataMenu.setText("Master Data");

        karyawanMenuItem.setText("Karyawan");
        karyawanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(karyawanMenuItem);

        pekerjaanMenuItem.setText("Pekerjaan");
        pekerjaanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekerjaanMenuItemActionPerformed(evt);
            }
        });
        masterDataMenu.add(pekerjaanMenuItem);

        jMenuBar1.add(masterDataMenu);

        transaksiMenu.setText("Transaksi");

        gajiMenuItem.setText("Gaji");
        gajiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiMenuItemActionPerformed(evt);
            }
        });
        transaksiMenu.add(gajiMenuItem);

        jMenuBar1.add(transaksiMenu);

        laporanMenu.setText("Laporan");

        gajiLaporanMenuItem.setText("Gaji");
        gajiLaporanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiLaporanMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(gajiLaporanMenuItem);
        laporanMenu.add(jSeparator3);

        karyawanLaporanMenuItem.setText("Karyawan");
        karyawanLaporanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanLaporanMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(karyawanLaporanMenuItem);

        pekerjaanLaporanMenuItem.setText("Pekerjaan");
        pekerjaanLaporanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekerjaanLaporanMenuItemActionPerformed(evt);
            }
        });
        laporanMenu.add(pekerjaanLaporanMenuItem);

        jMenuBar1.add(laporanMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mdiDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setEnableMenu(boolean aktif){
        masterDataMenu.setEnabled(aktif);
        transaksiMenu.setEnabled(aktif);
        laporanMenu.setEnabled(aktif);
    }
    
    private void setUkuranLokasiFrame(double skala, boolean tengah){
        Dimension dimensi = Toolkit.getDefaultToolkit().getScreenSize();
        setSize((int)(skala * dimensi.getWidth()), (int)(skala * dimensi.getHeight()));
        
        if (tengah){
            setLocation((int)((dimensi.getWidth() - getWidth())/2),
                    (int)((dimensi.getHeight() - getHeight())/2));
        }
    }
    
    private void deskripsiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deskripsiMenuItemActionPerformed
        // TODO add your handling code here:
        formDeskripsi.setVisible(true);
    }//GEN-LAST:event_deskripsiMenuItemActionPerformed

    private void pekerjaanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekerjaanMenuItemActionPerformed
        // TODO add your handling code here:
        if((formPekerjaan != null) && formPekerjaan.isVisible()){
            try {
                formPekerjaan.setSelected(true);
            } catch (PropertyVetoException ex) {}
        } else {
            formPekerjaan = new FormPekerjaan();
            mdiDesktopPane.add(formPekerjaan);
            formPekerjaan.setVisible(true);
        }
    }//GEN-LAST:event_pekerjaanMenuItemActionPerformed

    private void gajiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiMenuItemActionPerformed
        // TODO add your handling code here:
        if((formGaji != null) && formGaji.isVisible()){
            try {
                formGaji.setSelected(true);
            } catch (PropertyVetoException ex) {}
        } else {
            formGaji = new FormGaji();
            mdiDesktopPane.add(formGaji);
            formGaji.setVisible(true);
        }
    }//GEN-LAST:event_gajiMenuItemActionPerformed

    private void aplikasiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplikasiMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aplikasiMenuActionPerformed

    private void keluarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarMenuItemActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_keluarMenuItemActionPerformed

    private void karyawanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanMenuItemActionPerformed
        // TODO add your handling code here:
        if ((formKaryawan !=null) && formKaryawan.isVisible()){
            try {
                formKaryawan.setSelected(true);
            } catch (PropertyVetoException ex){}
        } else {
            formKaryawan = new FormKaryawan();
            mdiDesktopPane.add(formKaryawan);
            formKaryawan.setVisible(true);
        }
    }//GEN-LAST:event_karyawanMenuItemActionPerformed

    private void karyawanLaporanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanLaporanMenuItemActionPerformed
        // TODO add your handling code here:
        FormCetakKaryawan formCetak = new FormCetakKaryawan();
        mdiDesktopPane.add(formCetak);
        formCetak.setVisible(true);
    }//GEN-LAST:event_karyawanLaporanMenuItemActionPerformed

    private void pekerjaanLaporanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekerjaanLaporanMenuItemActionPerformed
        // TODO add your handling code here:
        FormCetakPekerjaan formCetak = new FormCetakPekerjaan();
        mdiDesktopPane.add(formCetak);
        formCetak.setVisible(true);
    }//GEN-LAST:event_pekerjaanLaporanMenuItemActionPerformed

    private void aksesMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aksesMenuItemActionPerformed
        // TODO add your handling code here:
        if (aksesMenuItem.getText().equals("Login")){
            new FormLogin(this, true).setVisible(true);
            if(!FormLogin.getUserLogin().equals("")){
                setEnableMenu(true);
                aksesMenuItem.setText("Logout");
            } else {
                setEnableMenu(false);
            }
        } else {
            aksesMenuItem.setText("Login");
            setEnableMenu(false);
        }
    }//GEN-LAST:event_aksesMenuItemActionPerformed

    private void gajiLaporanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiLaporanMenuItemActionPerformed
        // TODO add your handling code here:
        FormCetakGaji formCetak = new FormCetakGaji();
        mdiDesktopPane.add(formCetak);
        formCetak.setVisible(true);
    }//GEN-LAST:event_gajiLaporanMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aksesMenuItem;
    private javax.swing.JMenu aplikasiMenu;
    private javax.swing.JMenuItem deskripsiMenuItem;
    private javax.swing.JMenuItem gajiLaporanMenuItem;
    private javax.swing.JMenuItem gajiMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem karyawanLaporanMenuItem;
    private javax.swing.JMenuItem karyawanMenuItem;
    private javax.swing.JMenuItem keluarMenuItem;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenu masterDataMenu;
    private javax.swing.JDesktopPane mdiDesktopPane;
    private javax.swing.JMenuItem pekerjaanLaporanMenuItem;
    private javax.swing.JMenuItem pekerjaanMenuItem;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables

    private Object getDesktopPane() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
